apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-manager-deployment
  labels:
    app: schedulemanager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: schedulemanager
  template:
    metadata:
      labels:
        app: schedulemanager
    spec:
      containers:
      - name: schedule-manager
        image: nazmuls3/cfems_schedule_manager:v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3004
---
apiVersion: v1
kind: Service
metadata:
  name: schedule-manager-service
spec:
  selector:
    app: schedulemanager
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
