apiVersion: apps/v1
kind: Deployment
metadata:
  name: ib-simulator-deployment
  labels:
    app: ibsimulator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ibsimulator
  template:
    metadata:
      labels:
        app: ibsimulator
    spec:
      containers:
      - name: ib-simulator
        image: nazmuls3/cfems_simulator:v1.0.0
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: ib-simulator-service
spec:
  type: LoadBalancer
  selector:
    app: ibsimulator
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443