apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-server-deployment
  labels:
    app: fileserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fileserver
  template:
    metadata:
      labels:
        app: fileserver
    spec:
      containers:
      - name: file-server
        image: nazmuls3/cfems_file_server:v1.0.0
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: file-server-service
spec:
  type: LoadBalancer
  selector:
    app: fileserver
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
