apiVersion: apps/v1
kind: Deployment
metadata:
  name: dg-healthmanager-deployment
  labels:
    app: dghealthmanager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dghealthmanager
  template:
    metadata:
      labels:
        app: dghealthmanager
    spec:
      containers:
      - name: dg-healthmanager
        image: nazmuls3/cfems_dg_hm:v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: dg-healthmanager-service
spec:
  selector:
    app: dghealthmanager
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
