apiVersion: apps/v1
kind: Deployment
metadata:
  name: hbt-procssor-deployment
  labels:
    app: hbtprocssor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hbtprocssor
  template:
    metadata:
      labels:
        app: hbtprocssor
    spec:
      containers:
      - name: hbt-procssor
        image: nazmuls3/cfems_hbt_processor:v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: hbt-procssor-service
spec:
  selector:
    app: hbtprocssor
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
