apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbe-processor-deployment
  labels:
    app: rbeprocessor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rbeprocessor
  template:
    metadata:
      labels:
        app: rbeprocessor
    spec:
      containers:
      - name: rbe-processor
        image: nazmuls3/cfems_rbe_processor:v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3003
---
apiVersion: v1
kind: Service
metadata:
  name: rbe-processor-service
spec:
  selector:
    app: rbeprocessor
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
