apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-processor-deployment
  labels:
    app: configprocessor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: configprocessor
  template:
    metadata:
      labels:
        app: configprocessor
    spec:
      containers:
      - name: config-processor
        image: nazmuls3/cfems_config_processor:v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: config-processor-service
spec:
  selector:
    app: configprocessor
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
