using System;
using System.Collections.Generic;

namespace CFEMSDB.DB
{
    public partial class TblObjectBit
    {
        public string ColBuildingIdFk { get; set; } = null!;
        public string ColRtuIdFk { get; set; } = null!;
        public string ColEquipmentIdFk { get; set; } = null!;
        public bool ColIsAbove64 { get; set; }
        public bool? ColIfdBit1 { get; set; }
        public bool? ColIfdBit2 { get; set; }
        public bool? ColIfdBit3 { get; set; }
        public bool? ColIfdBit4 { get; set; }
        public bool? ColIfdBit5 { get; set; }
        public bool? ColIfdBit6 { get; set; }
        public bool? ColIfdBit7 { get; set; }
        public bool? ColIfdBit8 { get; set; }
        public bool? ColIfdBit9 { get; set; }
        public bool? ColIfdBit10 { get; set; }
        public bool? ColIfdBit11 { get; set; }
        public bool? ColIfdBit12 { get; set; }
        public bool? ColIfdBit13 { get; set; }
        public bool? ColIfdBit14 { get; set; }
        public bool? ColIfdBit15 { get; set; }
        public bool? ColIfdBit16 { get; set; }
        public DateTime? ColIfdBit1Date { get; set; }
        public DateTime? ColIfdBit2Date { get; set; }
        public DateTime? ColIfdBit3Date { get; set; }
        public DateTime? ColIfdBit4Date { get; set; }
        public DateTime? ColIfdBit5Date { get; set; }
        public DateTime? ColIfdBit6Date { get; set; }
        public DateTime? ColIfdBit7Date { get; set; }
        public DateTime? ColIfdBit8Date { get; set; }
        public DateTime? ColIfdBit9Date { get; set; }
        public DateTime? ColIfdBit10Date { get; set; }
        public DateTime? ColIfdBit11Date { get; set; }
        public DateTime? ColIfdBit12Date { get; set; }
        public DateTime? ColIfdBit13Date { get; set; }
        public DateTime? ColIfdBit14Date { get; set; }
        public DateTime? ColIfdBit15Date { get; set; }
        public DateTime? ColIfdBit16Date { get; set; }
        public bool? ColBit1 { get; set; }
        public bool? ColBit2 { get; set; }
        public bool? ColBit3 { get; set; }
        public bool? ColBit4 { get; set; }
        public bool? ColBit5 { get; set; }
        public bool? ColBit6 { get; set; }
        public bool? ColBit7 { get; set; }
        public bool? ColBit8 { get; set; }
        public bool? ColBit9 { get; set; }
        public bool? ColBit10 { get; set; }
        public bool? ColBit11 { get; set; }
        public bool? ColBit12 { get; set; }
        public bool? ColBit13 { get; set; }
        public bool? ColBit14 { get; set; }
        public bool? ColBit15 { get; set; }
        public bool? ColBit16 { get; set; }
        public bool? ColBit17 { get; set; }
        public bool? ColBit18 { get; set; }
        public bool? ColBit19 { get; set; }
        public bool? ColBit20 { get; set; }
        public bool? ColBit21 { get; set; }
        public bool? ColBit22 { get; set; }
        public bool? ColBit23 { get; set; }
        public bool? ColBit24 { get; set; }
        public bool? ColBit25 { get; set; }
        public bool? ColBit26 { get; set; }
        public bool? ColBit27 { get; set; }
        public bool? ColBit28 { get; set; }
        public bool? ColBit29 { get; set; }
        public bool? ColBit30 { get; set; }
        public bool? ColBit31 { get; set; }
        public bool? ColBit32 { get; set; }
        public bool? ColBit33 { get; set; }
        public bool? ColBit34 { get; set; }
        public bool? ColBit35 { get; set; }
        public bool? ColBit36 { get; set; }
        public bool? ColBit37 { get; set; }
        public bool? ColBit38 { get; set; }
        public bool? ColBit39 { get; set; }
        public bool? ColBit40 { get; set; }
        public bool? ColBit41 { get; set; }
        public bool? ColBit42 { get; set; }
        public bool? ColBit43 { get; set; }
        public bool? ColBit44 { get; set; }
        public bool? ColBit45 { get; set; }
        public bool? ColBit46 { get; set; }
        public bool? ColBit47 { get; set; }
        public bool? ColBit48 { get; set; }
        public bool? ColBit49 { get; set; }
        public bool? ColBit50 { get; set; }
        public bool? ColBit51 { get; set; }
        public bool? ColBit52 { get; set; }
        public bool? ColBit53 { get; set; }
        public bool? ColBit54 { get; set; }
        public bool? ColBit55 { get; set; }
        public bool? ColBit56 { get; set; }
        public bool? ColBit57 { get; set; }
        public bool? ColBit58 { get; set; }
        public bool? ColBit59 { get; set; }
        public bool? ColBit60 { get; set; }
        public bool? ColBit61 { get; set; }
        public bool? ColBit62 { get; set; }
        public bool? ColBit63 { get; set; }
        public bool? ColBit64 { get; set; }
        public DateTime? ColBit1Date { get; set; }
        public DateTime? ColBit2Date { get; set; }
        public DateTime? ColBit3Date { get; set; }
        public DateTime? ColBit4Date { get; set; }
        public DateTime? ColBit5Date { get; set; }
        public DateTime? ColBit6Date { get; set; }
        public DateTime? ColBit7Date { get; set; }
        public DateTime? ColBit8Date { get; set; }
        public DateTime? ColBit9Date { get; set; }
        public DateTime? ColBit10Date { get; set; }
        public DateTime? ColBit11Date { get; set; }
        public DateTime? ColBit12Date { get; set; }
        public DateTime? ColBit13Date { get; set; }
        public DateTime? ColBit14Date { get; set; }
        public DateTime? ColBit15Date { get; set; }
        public DateTime? ColBit16Date { get; set; }
        public DateTime? ColBit17Date { get; set; }
        public DateTime? ColBit18Date { get; set; }
        public DateTime? ColBit19Date { get; set; }
        public DateTime? ColBit20Date { get; set; }
        public DateTime? ColBit21Date { get; set; }
        public DateTime? ColBit22Date { get; set; }
        public DateTime? ColBit23Date { get; set; }
        public DateTime? ColBit24Date { get; set; }
        public DateTime? ColBit25Date { get; set; }
        public DateTime? ColBit26Date { get; set; }
        public DateTime? ColBit27Date { get; set; }
        public DateTime? ColBit28Date { get; set; }
        public DateTime? ColBit29Date { get; set; }
        public DateTime? ColBit30Date { get; set; }
        public DateTime? ColBit31Date { get; set; }
        public DateTime? ColBit32Date { get; set; }
        public DateTime? ColBit33Date { get; set; }
        public DateTime? ColBit34Date { get; set; }
        public DateTime? ColBit35Date { get; set; }
        public DateTime? ColBit36Date { get; set; }
        public DateTime? ColBit37Date { get; set; }
        public DateTime? ColBit38Date { get; set; }
        public DateTime? ColBit39Date { get; set; }
        public DateTime? ColBit40Date { get; set; }
        public DateTime? ColBit41Date { get; set; }
        public DateTime? ColBit42Date { get; set; }
        public DateTime? ColBit43Date { get; set; }
        public DateTime? ColBit44Date { get; set; }
        public DateTime? ColBit45Date { get; set; }
        public DateTime? ColBit46Date { get; set; }
        public DateTime? ColBit47Date { get; set; }
        public DateTime? ColBit48Date { get; set; }
        public DateTime? ColBit49Date { get; set; }
        public DateTime? ColBit50Date { get; set; }
        public DateTime? ColBit51Date { get; set; }
        public DateTime? ColBit52Date { get; set; }
        public DateTime? ColBit53Date { get; set; }
        public DateTime? ColBit54Date { get; set; }
        public DateTime? ColBit55Date { get; set; }
        public DateTime? ColBit56Date { get; set; }
        public DateTime? ColBit57Date { get; set; }
        public DateTime? ColBit58Date { get; set; }
        public DateTime? ColBit59Date { get; set; }
        public DateTime? ColBit60Date { get; set; }
        public DateTime? ColBit61Date { get; set; }
        public DateTime? ColBit62Date { get; set; }
        public DateTime? ColBit63Date { get; set; }
        public DateTime? ColBit64Date { get; set; }
    }
}
